export const fake_tags = [
  // Size
  "x-small",
  "small",
  "medium",
  "large",
  "x-large",

  // Color
  "red",
  "blue",
  "green",
  "yellow",
  "purple",

  // Occasion
  "casual",
  "formal",
  "wedding",
  "beach",

  // Time
  "summer",
  "winter",
  "spring",
  "fall",
  "year-round",

  // Material
  "cotton",
  "wool",
  "leather",
  "polyester",
  "denim",

  // Style
  "vintage",
  "modern",
  "bohemian",
  "sporty",
  "elegant",

  // Miscellaneous
  "floral",
  "striped",
  "dotted",
  "solid",
  "graphic",
];

export const fake_cards = [
  {
    title: "Cozy Winter Sweater",
    description: "A warm and cozy sweater perfect for winter days.",
    tags: ["x-large", "red", "winter", "cotton", "casual"],
    url: "https://example.com/cozy-winter-sweater",
  },
  {
    title: "Stylish Summer Dress",
    description: "A lightweight dress ideal for summer outings.",
    tags: ["medium", "blue", "summer", "floral", "elegant"],
    url: "https://example.com/stylish-summer-dress",
  },
  {
    title: "Classic Leather Jacket",
    description: "A timeless piece that never goes out of style.",
    tags: ["large", "black", "year-round", "leather", "modern"],
    url: "https://example.com/classic-leather-jacket",
  },
  {
    title: "Trendy Sneakers",
    description: "Comfortable sneakers for everyday wear.",
    tags: ["medium", "white", "year-round", "denim", "sporty"],
    url: "https://example.com/trendy-sneakers",
  },
  {
    title: "Elegant Evening Gown",
    description: "A stunning gown for special occasions.",
    tags: ["x-small", "purple", "formal", "silk", "elegant"],
    url: "https://example.com/elegant-evening-gown",
  },
  {
    title: "Casual T-Shirt",
    description: "A basic t-shirt for relaxed days.",
    tags: ["large", "gray", "casual", "cotton", "solid"],
    url: "https://example.com/casual-t-shirt",
  },
  {
    title: "Beach Shorts",
    description: "Perfect for sunny days at the beach.",
    tags: ["medium", "yellow", "beach", "polyester", "sporty"],
    url: "https://example.com/beach-shorts",
  },
  {
    title: "Chic Handbag",
    description: "A stylish handbag to complete your outfit.",
    tags: ["one-size", "brown", "year-round", "leather", "modern"],
    url: "https://example.com/chic-handbag",
  },
  {
    title: "Warm Scarf",
    description: "Stay warm with this cozy scarf.",
    tags: ["one-size", "red", "winter", "wool", "solid"],
    url: "https://example.com/warm-scarf",
  },
  {
    title: "Athletic Leggings",
    description: "Perfect for workouts or casual wear.",
    tags: ["small", "black", "year-round", "polyester", "sporty"],
    url: "https://example.com/athletic-leggings",
  },
  {
    title: "Lightweight Jacket",
    description: "Ideal for breezy spring days.",
    tags: ["medium", "green", "spring", "nylon", "casual"],
    url: "https://example.com/lightweight-jacket",
  },
  {
    title: "Formal Dress Shirt",
    description: "A crisp shirt for formal events.",
    tags: ["large", "white", "formal", "cotton", "classic"],
    url: "https://example.com/formal-dress-shirt",
  },
  {
    title: "Casual Sneakers",
    description: "Versatile sneakers for everyday use.",
    tags: ["medium", "gray", "year-round", "canvas", "sporty"],
    url: "https://example.com/casual-sneakers",
  },
  {
    title: "Graphic T-Shirt",
    description: "Express yourself with unique graphics.",
    tags: ["small", "black", "casual", "cotton", "graphic"],
    url: "https://example.com/graphic-t-shirt",
  },
  {
    title: "Beach Cover-Up",
    description: "Lightweight cover-up for beach days.",
    tags: ["medium", "white", "beach", "linen", "casual"],
    url: "https://example.com/beach-cover-up",
  },
  {
    title: "Vintage Denim Jacket",
    description: "A classic denim jacket for a retro look.",
    tags: ["large", "blue", "year-round", "denim", "vintage"],
    url: "https://example.com/vintage-denim-jacket",
  },
  {
    title: "Soft Pajama Set",
    description: "Comfortable pajamas for a good night's sleep.",
    tags: ["medium", "pink", "home", "cotton", "relaxed"],
    url: "https://example.com/soft-pajama-set",
  },
  {
    title: "Sporty Swim Trunks",
    description: "Perfect for swimming and water activities.",
    tags: ["small", "blue", "summer", "polyester", "sporty"],
    url: "https://example.com/sporty-swim-trunks",
  },
  {
    title: "Classic Wool Coat",
    description: "A timeless coat for cold weather.",
    tags: ["x-large", "black", "winter", "wool", "elegant"],
    url: "https://example.com/classic-wool-coat",
  },
  {
    title: "Funky Patterned Socks",
    description: "Add some fun to your outfit with these socks.",
    tags: ["one-size", "multi-color", "casual", "cotton", "quirky"],
    url: "https://example.com/funky-patterned-socks",
  },
  {
    title: "Elegant Clutch Bag",
    description: "Perfect for formal events.",
    tags: ["one-size", "gold", "formal", "leather", "elegant"],
    url: "https://example.com/elegant-clutch-bag",
  },
  {
    title: "Floral Print Maxi Dress",
    description: "Beautiful dress for summer occasions.",
    tags: ["medium", "floral", "summer", "cotton", "elegant"],
    url: "https://example.com/floral-print-maxi-dress",
  },
  {
    title: "Warm Beanie",
    description: "Keep your head warm during winter.",
    tags: ["one-size", "navy", "winter", "wool", "casual"],
    url: "https://example.com/warm-beanie",
  },
  {
    title: "Comfortable Slippers",
    description: "Soft slippers for lounging at home.",
    tags: ["medium", "gray", "home", "fleece", "relaxed"],
    url: "https://example.com/comfortable-slippers",
  },
  {
    title: "Chic Sunglasses",
    description: "Stylish sunglasses for sunny days.",
    tags: ["one-size", "black", "summer", "plastic", "modern"],
    url: "https://example.com/chic-sunglasses",
  },
  {
    title: "Classic Backpack",
    description: "A reliable backpack for everyday use.",
    tags: ["one-size", "green", "casual", "canvas", "functional"],
    url: "https://example.com/classic-backpack",
  },
  {
    title: "Stylish Fedora Hat",
    description: "Add flair to your outfit with this hat.",
    tags: ["one-size", "beige", "year-round", "wool", "fashion"],
    url: "https://example.com/stylish-fedora-hat",
  },
  {
    title: "Trendy Crop Top",
    description: "A fashionable crop top for summer.",
    tags: ["small", "white", "summer", "cotton", "trendy"],
    url: "https://example.com/trendy-crop-top",
  },
  {
    title: "Classic Chinos",
    description: "Versatile pants for casual or formal wear.",
    tags: ["medium", "beige", "year-round", "cotton", "classic"],
    url: "https://example.com/classic-chinos",
  },
  {
    title: "Casual Button-Up Shirt",
    description: "A comfortable button-up for everyday wear.",
    tags: ["large", "light-blue", "casual", "cotton", "modern"],
    url: "https://example.com/casual-button-up-shirt",
  },
  {
    title: "Elegant Ankle Boots",
    description: "Stylish boots for fall and winter.",
    tags: ["size-8", "black", "fall", "leather", "elegant"],
    url: "https://example.com/elegant-ankle-boots",
  },
  {
    title: "Lightweight Scarf",
    description: "A versatile scarf for layering.",
    tags: ["one-size", "gray", "year-round", "silk", "fashion"],
    url: "https://example.com/lightweight-scarf",
  },
  {
    title: "Classic Black Belt",
    description: "A simple yet essential accessory.",
    tags: ["one-size", "black", "year-round", "leather", "classic"],
    url: "https://example.com/classic-black-belt",
  },
  {
    title: "Retro Sunglasses",
    description: "Add a retro vibe to your look.",
    tags: ["one-size", "tortoise-shell", "summer", "plastic", "retro"],
    url: "https://example.com/retro-sunglasses",
  },
  {
    title: "Comfortable Yoga Pants",
    description: "Ideal for yoga and workouts.",
    tags: ["medium", "black", "year-round", "spandex", "sporty"],
    url: "https://example.com/comfortable-yoga-pants",
  },
  {
    title: "Stylish Cardigan",
    description: "Perfect for layering in cooler weather.",
    tags: ["large", "cream", "fall", "cotton", "fashion"],
    url: "https://example.com/stylish-cardigan",
  },
  {
    title: "Vintage Floral Blouse",
    description: "A charming blouse for casual outings.",
    tags: ["medium", "floral", "spring", "cotton", "vintage"],
    url: "https://example.com/vintage-floral-blouse",
  },
  {
    title: "Classic White Sneakers",
    description: "Essential sneakers for any wardrobe.",
    tags: ["medium", "white", "year-round", "canvas", "casual"],
    url: "https://example.com/classic-white-sneakers",
  },
  {
    title: "Chic Wrap Dress",
    description: "A flattering wrap dress for any occasion.",
    tags: ["small", "black", "formal", "cotton", "elegant"],
    url: "https://example.com/chic-wrap-dress",
  },
  {
    title: "Stylish High-Heeled Shoes",
    description: "Elevate your outfit with these heels.",
    tags: ["size-7", "red", "formal", "leather", "fashion"],
    url: "https://example.com/stylish-high-heeled-shoes",
  },
  {
    title: "Casual Cargo Shorts",
    description: "Comfortable shorts for summer adventures.",
    tags: ["medium", "khaki", "summer", "cotton", "sporty"],
    url: "https://example.com/casual-cargo-shorts",
  },
  {
    title: "Trendy Jumpsuit",
    description: "A fashionable one-piece outfit.",
    tags: ["medium", "black", "year-round", "cotton", "trendy"],
    url: "https://example.com/trendy-jumpsuit",
  },
  {
    title: "Classic Canvas Tote",
    description: "A durable tote for everyday use.",
    tags: ["one-size", "blue", "casual", "canvas", "functional"],
    url: "https://example.com/classic-canvas-tote",
  },
  {
    title: "Lightweight Travel Backpack",
    description: "Perfect for your next adventure.",
    tags: ["one-size", "gray", "travel", "nylon", "functional"],
    url: "https://example.com/lightweight-travel-backpack",
  },
  {
    title: "Soft Knit Sweater",
    description: "Stay cozy with this soft knit sweater.",
    tags: ["large", "pink", "winter", "wool", "casual"],
    url: "https://example.com/soft-knit-sweater",
  },
  {
    title: "Classic Fedora Hat",
    description: "A stylish accessory for any outfit.",
    tags: ["one-size", "black", "year-round", "felt", "fashion"],
    url: "https://example.com/classic-fedora-hat",
  },
  {
    title: "Comfortable Lounge Pants",
    description: "Relax in these comfy lounge pants.",
    tags: ["medium", "gray", "home", "cotton", "relaxed"],
    url: "https://example.com/comfortable-lounge-pants",
  },
  {
    title: "Sporty Windbreaker",
    description: "Stay dry and stylish with this windbreaker.",
    tags: ["large", "navy", "spring", "nylon", "sporty"],
    url: "https://example.com/sporty-windbreaker",
  },
];
