import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/component/nav"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const noto = Noto_Sans({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={noto.className}>
      <body className="min-h-screen flex flex-col border-2 border-red-500">
        <main className="flex-1 border-2 border-blue-500">{children}</main>
        <Navigation />
      </body>
    </html>
  );
}
